# Generated by Django 4.0.2 on 2023-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postal_code',
        ),
    ]
