# Generated by Django 4.0.2 on 2023-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
